# We have implemented four services:
# 1. seed: This service is responsible for seeding the database with initial data.
# 2. ollama: This service runs the Ollama server.
# 3. api: This service runs the REST API built with Flask.
# 4. streamlit: This service runs the Streamlit admin interface.
#
# The ollama service will be built from the Dockerfile in the docker/ollama/ directory, exposed on port 11434.
# The REST API will be built from the Dockerfile in the docker/flask/ directory, exposed on port 5000.
# The streamlit app will be built from the Dockerfile in the docker/streamlit/ directory, exposed on port 8501.

# In order to run the containers:
# 1. Create a .env file in the same directory as this compose.yaml file with the following content:
#    RESEND_API_KEY=your_resend_api_key
#    RESEND_FROM_EMAIL=your_resend_from_email
#    OLLAMA_MODEL=the_name_of_your_ollama_model
# 2. Open Docker Desktop and the terminal.
# 3. Navigate to the directory containing this compose.yaml file.
# 4. Run the command 'docker compose up'
# 5. Go to http://localhost:11434/api/tags to check if ${OLLAMA_MODEL} is available.
# 6. If ${OLLAMA_MODEL} is not available, go to ollama's container, open the terminal, and run the command 'ollama run ${OLLAMA_MODEL}'.
services:
  seed:
    build:
      context: ./
      dockerfile: ./docker/migrations/Dockerfile
    
    volumes:
      - ./database/database.db:/app/database.db

    command: python seed.py

  ollama:
    build:
      context: ./
      dockerfile: ./docker/ollama/Dockerfile
    
    volumes:
      - ollama:/root/.ollama

    ports:
      - "11434:11434"

  api:
    build:
      context: ./
      dockerfile: ./docker/flask/Dockerfile

    ports:
      - "5000:5000"
    
    command: python api.py

    depends_on:
      - seed

    volumes:
      - ./database/database.db:/app/database.db

  streamlit:
    build:
      context: ./
      dockerfile: ./docker/streamlit/Dockerfile

    ports:
      - "8501:8501"
    
    command: streamlit run admin.py --server.port=8501 --server.address=0.0.0.0

    depends_on:
      - seed
      - ollama

    volumes:
      - ./database/database.db:/app/database.db
    
    environment:
    - RESEND_API_KEY=${RESEND_API_KEY}
    - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
    - OLLAMA_URL=http://ollama:11434/api/generate
    - OLLAMA_MODEL=${OLLAMA_MODEL}

volumes:
  ollama: {}