# We have implemented three services, one for the REST API, one for the streamlit app, and one for seeding the database.
# The REST API will be built from the Dockerfile in the docker/flask/ directory, exposed on port 5000.
# The streamlit app will be built from the Dockerfile in the docker/streamlit/ directory, exposed on port 8501.

# In order to run the containers:
# 1. Create a .env file in the same directory as this compose.yaml file with the following content:
#    RESEND_API_KEY=your_resend_api_key
#    RESEND_FROM_EMAIL=your_resend_from_email
# 2. Open Docker Desktop and the terminal.
# 3. Navigate to the directory containing this compose.yaml file.
# 4. Run the command 'docker compose up'
services:
  seed:
    build:
      context: ./
      dockerfile: ./docker/migrations/Dockerfile
    
    volumes:
      - ./database/database.db:/app/database.db

    command: python seed.py

  api:
    build:
      context: ./
      dockerfile: ./docker/flask/Dockerfile

    ports:
      - "5000:5000"
    
    command: python api.py

    depends_on:
      - seed

    volumes:
      - ./database/database.db:/app/database.db

  streamlit:
    build:
      context: ./
      dockerfile: ./docker/streamlit/Dockerfile

    ports:
      - "8501:8501"
    
    command: streamlit run admin.py --server.port=8501 --server.address=0.0.0.0

    depends_on:
      - seed

    volumes:
      - ./database/database.db:/app/database.db
    
    environment:
    - RESEND_API_KEY=${RESEND_API_KEY}
    - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
